kind: Namespace
apiVersion: v1
metadata:
  name: sample-api-one
  labels:
    name: sample-api-one
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api-one
  namespace: sample-api-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-api-one
  template:
    metadata:
      labels:
        app: sample-api-one
    spec:
      containers:
        - name: sampleapilogs-kubernetes
          image: parisadocker/logs:1708
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - name: http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sample-api-one
  namespace: sample-api-one
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP # The protocol the SERVICE will listen to
  selector:
    app: sample-api-one
