apiVersion: v1
kind: Pod
metadata:
  name: az-aks-workload-identity-sample
  namespace: ${NAMESPACE}
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-identity-sa
  containers:
    - image: ghcr.io/azure/azure-workload-identity/msal-go
      name: oidc
      env:
        - name: KEYVAULT_URL
          value: ${KEYVAULT_URL}
        - name: SECRET_NAME
          value: secret-sauce
  nodeSelector:
    kubernetes.io/os: linux
