apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-api-logs-unhealty
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-api-logs-unhealty
  template:
    metadata:
      labels:
        app: sample-api-logs-unhealty
    spec:
      containers:
        - name: sampleapilogs-kubernetes-unhealty
          image: parisadocker/logs:1701
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          ports:
            - name: http
              containerPort: 80
